### PR TITLE
Madness_over_parsec: new parsec nb tasks management for PR 26 in PaRSEC that was recently merged

### PR DESCRIPTION
**Pull request by therault**
This changes the way madness_over_parsec handles the nb_tasks / submits tasks.

This change is necessary to work with the recent changes in parsec that will allow sparse / undeteremined execution spaces for task classes, enabling a better handling of the tree algorithms.

### CODE REVIEW

**Comment by evaleev** [comment]
Thomas, this seems to include many formatting-only changes such as spaces -> tabs (or vice versa), extra spaces, etc.

**Comment by therault** [comment]
Yes, sorry about that. It makes the patch harder to read.
I re-indented everything according to the PaRSEC coding style. Bad habit.
I’ll change the patch so that I push only changes on significant lines.

Thomas

**Comment by therault** [comment]
I left the space reformatting in parsec.cc, since it is a new file for madness anyway, but I reverted all formatting changes in thread.cc and thread.h

The PR should be easier to read at this point.

**Comment by aguermou** [comment]
Hello guys,

The modifications Thomas added to madness are now merged.
Please update both parsec and madness (especially if you update parsec, 
you will have to update madness since some updates in PaRSEC are used in 
madness).

Amina

**Pull request merged**
